# -*- coding: utf-8 -*-
"""Compare a bare recurrence of an intrinsic change with a familiar process."""


def _source_frames(source):
    import morphology as M
    import corrector as E
    from semantic_roles import nominal_roles
    from literal_examples import protected_ranges, overlaps
    result=[];lo=0;protected=None
    for hi,end in [(m.start(),m.end()) for m in M.COLUMN_SEPARATOR.finditer(source)]+[(len(source),len(source))]:
        field=source[lo:hi]
        if not field.startswith('再'):
            lo=end
            continue
        # A tokenizer may merge a productive prefix with its noun. The
        # unchanged native prefix and whole following action prove the same
        # source structure independently of that best-path aggregation.
        prefixes=[rd for pos,form,base,rd in M.dictionary_inflections(field[:1]) or ()
                  if pos.startswith('接頭詞,名詞接続,') and base==field[:1]]
        actions=[rd for pos,form,base,rd in M.dictionary_inflections(field[1:]) or ()
                 if pos.startswith('名詞,サ変接続,') and base==field[1:]]
        readings={a+b for a in prefixes for b in actions}
        if (len(readings)==1 and 'intrinsic_process' in nominal_roles(field[1:])
                and E._table_cost(field) is None):
            if protected is None:protected=protected_ranges(source)
            if not overlaps(lo,hi,protected):
                result.append(dict(start=lo,end=hi,reading=next(iter(readings))))
        lo=end
    return tuple(result)


def _proposals(reading):
    import contextual_repair as C
    import corrector as E
    import morphology as M
    from ime_language import JapaneseIME
    out=[]
    with JapaneseIME() as ime:
        if not ime.available:return ()
        for repair in C.key_repairs(reading):
            if repair.operation!='omission':continue
            face=ime.convert(repair.reading)
            if not face or E._table_cost(face) is None:continue
            parts=M.tokenize(face)
            if (len(parts)!=2 or parts[0].pos!='名詞'
                    or parts[1].surface!='化' or parts[1].pos_sub!='接尾:サ変接続'
                    or not M.native_spelling_only(repair.reading,face)):continue
            out.append((face,repair))
    return tuple(out)


def _bare_sequence_frames(source):
    """Compare a reviewed specialist activity with a physical control reading.

    Rarity alone proves nothing. Require a bare native sahen head, its real
    suru/te link, a complete ordinary action in this field, and a positively
    fitting control candidate generated by the common physical-key model.
    Original domain links, explicit selection and quotations take precedence.
    """
    import morphology as M
    import kango_tier as K
    import contextual_repair as C
    from reading_segments import native_bare_action_faces
    from semantic_roles import ACTION_CONTROL_PREDICATES,action_note_support
    from last_choice import surface_for_reading
    from literal_examples import protected_ranges,overlaps
    out=[];lo=0;protected=None
    for hi,next_lo in [(m.start(),m.end()) for m in M.COLUMN_SEPARATOR.finditer(source)]+[(len(source),len(source))]:
        raw=source[lo:hi];left=len(raw)-len(raw.lstrip());field=raw.strip().rstrip(' 。！？!?')
        start=lo+left;lo=next_lo
        if field.count('して')!=1:continue
        head,following=field.split('して')
        if not head:continue
        if all('ぁ'<=c<='ゖ' for c in head):
            rd=head
            faces=tuple(face for face in K._explicit_reading_faces().get(rd,())
                if any(pos.startswith('名詞,サ変接続,') and base==face and reading==rd
                    for pos,form,base,reading in M.dictionary_inflections(face) or ()))
        else:
            forms=tuple(row for row in M.dictionary_inflections(head) or ()
                        if row[0].startswith('名詞,サ変接続,') and row[2]==head)
            reads={row[3] for row in forms}
            if len(reads)!=1:continue
            rd=next(iter(reads));faces=(head,)
        if not faces or any(K.known_usage_tier(face)!=3 for face in faces):continue
        if all('ぁ'<=c<='ゖ' for c in following):
            right=native_bare_action_faces(following)
        else:
            right=tuple(dict.fromkeys(base for pos,form,base,reading in M.dictionary_inflections(following) or ()
                if pos.startswith('名詞,サ変接続,') and base==following and K.known_usage_tier(base) in (1,2)))
        if not right:continue
        if any(action_note_support(face,after) for face in faces for after in right):continue
        if surface_for_reading(rd) in faces:continue
        # A whole phrase selection uses its full native reading, even when
        # this field writes the following action in kanji or raw kana.
        originals={field}|{face+'して'+after for face in faces for after in right}
        selected=False
        for after in right:
            for pos,form,base,after_reading in M.dictionary_inflections(after) or ():
                if pos.startswith('名詞,サ変接続,') and base==after:
                    if surface_for_reading(rd+'して'+after_reading) in originals:
                        selected=True;break
            if selected:break
        if selected:continue
        proposals=[]
        for repair in C.key_repairs(rd):
            if repair.operation!='adjacent_substitution':continue
            for face in native_bare_action_faces(repair.reading):
                if (K.known_usage_tier(face)==1 and face in ACTION_CONTROL_PREDICATES
                    and any(action_note_support(face,after) for after in right)):
                    proposals.append((face,repair))
        if not proposals:continue
        if protected is None:protected=protected_ranges(source)
        if overlaps(start,start+len(field),protected):continue
        out.append(dict(kind='bare_action_control',start=start,end=start+len(head),reading=rd,
            evidence_start=start,evidence_end=start+len(field),following_actions=right,
            proposals=tuple(proposals),reason='対象が示されない専門動作より、同じ欄の動作に合う一般的な手順の操作を比較します'))
    return tuple(out)


def frames(source):
    from ime_inverse_gate import _CORRECTION_CACHE
    cache=_CORRECTION_CACHE.get();key=('process_familiarity',source)
    if cache is not None and key in cache:return cache[key]
    result=[]
    for frame in _source_frames(source):
        proposals=_proposals(frame['reading'])
        # This is a comparative familiarity judgment. A lack of corpus or
        # dictionary entry alone is not an assertion that the source is wrong.
        if proposals:result.append(dict(frame,proposals=proposals))
    result.extend(_bare_sequence_frames(source))
    out=tuple(result)
    if cache is not None:cache[key]=out
    return out


def options(target,reading):
    for f in frames(target.source):
        if (f['start'],f['end'])!=(target.start,target.end) or reading.text!=f['reading']:continue
        for face,repair in f['proposals']:
            yield reading,repair,('ime_clause',(face,))


def supports_replacement(target,surface,reading):
    return any(face==surface and (reading is None or repair.reading==reading)
               for f in frames(target.source)
               if (f['start'],f['end'])==(target.start,target.end)
               for face,repair in f['proposals'])


def meaning_evidence(target,surface):
    import morphology as M
    for f in frames(target.source):
        if f.get('kind')=='bare_action_control' and (f['start'],f['end'])==(target.start,target.end):
            if any(face==surface for face,repair in f['proposals']):
                return dict(source='specialist_activity',candidate='action_control',
                            meaning=f['reason'],following_actions=f['following_actions'])
    if not any((f['start'],f['end'])==(target.start,target.end)
               for f in frames(target.source)):return None
    parts=M.tokenize(surface)
    if (len(parts)==2 and parts[0].pos=='名詞' and parts[0].has_reading
            and parts[1].surface=='化' and parts[1].pos=='名詞'
            and parts[1].pos_sub=='接尾:サ変接続'):
        return dict(source='intrinsic_process',candidate='nominal_transformation',
                    meaning='原文と同じく状態の変化を表す名詞')
    return None
